### ISSUE TITLE
Could sexp-grammar be made Safe?

### ISSUE THREAD

**Issue by Munksgaard** [esmolanka/sexp-grammar#10]
I'm interested in using sexp-grammar for my project, but I want to define isomorphisms for types defined in [safe](https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/safe-haskell.html) modules. What would it take for sexp-grammar to be safe, so I could import it?

**Comment by esmolanka** [comment]
Unfortunately, some dependencies of sexp-grammar are themselves not -XSafe, e.g.`Data.Coerce` and `Data.Scientific`. 

This prevents me from making sexp-grammar `-XSafe`:

```
Base.hs:44:1: error:
     Data.Coerce: Can't be safely imported!
     The module itself isn't safe.
```

**Comment by Munksgaard** [comment]
I see. I'm not well-versed in Safe Haskell, but would it make sense to make sexp-grammar Trustworthy then? I guess it might just convey a false sense of security?

**Comment by esmolanka** [comment]
Let me check is Trustworthy is doable. The library does not do anything risky or shady, so it should be doable.

**Comment by Munksgaard** [comment]
We've found a way around requiring Safe sexp-grammar (basically by making the importing modules `Trustworthy` instead of `Safe`, so we don't have an urgent need for this any more. Unless you're keen to do it any way, I'll suggest we close this issue.

**Comment by esmolanka** [comment]
Yes, that's probably what I have to do in the library, too. `Safe` basically means "please check if I don't do or import anything risky" whereas `Trustworthy` means "trust me, I just checked it myself".

So some modules that import non-`Safe` libraries have to be annotated as `Trustworthy`, and the rest might go as `Safe`. I might include this into the next release, too.

**Comment by Munksgaard** [comment]
Sounds great. Thank you for your work!

**Comment by esmolanka** [comment]
Added some annotations in [f8760798](https://github.com/esmolanka/sexp-grammar/commit/f8760798bd897522ff5ee3edfcaa43446523a26a).
