### ISSUE TITLE
Data.Functor.Foldable.Fix has been moved to Data.Fix

### ISSUE THREAD

**Issue by Munksgaard** [esmolanka/sexp-grammar#12]
Since version 5.2 [recursion-schemes](https://hackage.haskell.org/package/recursion-schemes) doesn't include it's own `Fix` any more, but relies on [data-fix](https://hackage.haskell.org/package/data-fix-0.3.0). If I've understood things correctly, this is not an issue when using stack, because it uses a fixed snapshot of the package repository, but I had problems compiling sexp-grammar using cabal. It would be if either sexp-grammar was updated to use the new Data.Fix module, or if the version of recursion-schemes inside [sexp-grammar.cabal](https://github.com/esmolanka/sexp-grammar/blob/master/sexp-grammar/sexp-grammar.cabal#L52) were updated to specify `<5.2`.

**Comment by Munksgaard** [comment]
I can make a pull request with the latter fix, if you want, but I didn't understand the error messages I was getting while trying to use Data.Fix instead of Data.Functor.Foldable.Fix.

**Comment by esmolanka** [comment]
Sure, it definitely makes sense to relax `recursion-schemes` upper bounds, so it will reuse `Data.Fix`.

(Migrating to `data-fix` is a more invasive change so it'll probably be harder to make it backwards compatible. I'd like to support old versions of stackage snapshots and GHCs)
